[package]
name = "minigrep"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
human-panic = "1.1.0"
serde_json = "1.0.93"


[profile.release]
strip = true
opt-level = "z"
lto = true
